name: Publish to npm

on:
  push:
    tags:
      - '@pb4/ng-fluentui_v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Build library
        run: npm run build ng-fluentui

      - name: Publish to npm
        run: |
          cd dist/ng-fluentui
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
